### ISSUE TITLE
preserve val between replace + find next

### ISSUE THREAD

**Issue by ethanj** [vilic/vscode-sensitive-replace#1]
A couple of features would really jack up the utility..
replace - using previously set replacement string
replace + find next - equivalent to editor.action.replaceOne

Make sure to expose these for key assignment, and the extension could pretty completely replace the standard find / replace for non-regex workflows.

**Comment by MatthewTrout** [comment]
Agreed, I feel like this utility is most useful in conjunction with find and replace

**Comment by vilicvane** [comment]
I think this is now resolved by the built-in replace improvement of VS Code.
